### ISSUE TITLE
v2.0 Checklist

### ISSUE THREAD

**Issue by jdevries3133** [jdevries3133/teacher_helper#10]
- [x] make `grader.graders` generalizable. Create a base `Grader` class which defines
      the abstract grading framework
- [x] remove `IterCSV`, replace with `csv.DictReader`
- [ ] #13
- [ ] #12
- [x] remove `sis_proxy` from `teacherhelper.grader`. It is not needed outside
      the context of the term 2 project
- [x] #11
      do some copy-pasting so that the test for the deprecated `teacherhelper.Helper`
      interface remains
- [x] move `DocWriter` into a separate module from `grader`. Add template
      replacement targets to `add_page` so that the `DocWriter` class can be
      concrete
- [x] document `DocWriter`

**Comment by jdevries3133** [comment]
Remaining items will be left for 2.1.0. I added warnings in the docs about untested code in the google classroom module, and `teacherhelper.test` does exercise `teacherhelper.sis`, it just does so through the old interface.

**Comment by jdevries3133** [comment]
closing because google module tests were spun off as separate issues for a later time
